### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by mayowadavid** [YaphetS1/WiFi-Direct-File-Transfer-App#13]
Hi, @YaphetS1 I am a graphics designer. I will like to know if you want me to create a logo for your project.

**Comment by YaphetS1** [comment]
Hi, @mayowadavid Yea, it would be great. Maybe we contact by telegram or email?

**Comment by mayowadavid** [comment]
@YaphetS1 no problem. May i know your telegram username?
Mayowadavid is also my telegram username.

**Comment by mayowadavid** [comment]
@YaphetS1 i have made the pull request based on the green and blue icon as discussed on telegram, this is the link to png and editable files **[here](https://drive.google.com/open?id=1_2txgOcpAziCjI6f0FmfON-uxN94lKIT)**

**Comment by YaphetS1** [comment]
Thank you!

**Comment by mayowadavid** [comment]
Am glad you like it.
