### ISSUE TITLE
Unable to Send and Receive files  

### ISSUE THREAD

**Issue by pandey-saumya** [YaphetS1/WiFi-Direct-File-Transfer-App#20]
The application builds and runs without any error. But the available devices are not discovered by the application and the send/ receive functionality is not working.

**Comment by YaphetS1** [comment]
@psam3196 Thank for your vote, what are these devices?

**Comment by pandey-saumya** [comment]
@YaphetS1 I tried to run the application on OnePlus 6 and HTC.

**Comment by YaphetS1** [comment]
@psam3196 Version Android? Android on the stock version or custom?
Because in the stock version of android everything works

**Comment by pandey-saumya** [comment]
@YaphetS1 HTC-Android Lollipop 5.1.1 with custom Android (HTC Sense).
OnePlus 6- Android Pie 9 with Oxygen OS (Custom Android)

**Comment by YaphetS1** [comment]
@psam3196 So, on some devices, this app may not working, because some firms had modify stock released Google protocols. If you use a custom android, then it probably won't working
